# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GenAY <- function(W, Y, Rho) {
    .Call(`_bpNet_GenAY`, W, Y, Rho)
}

rhofit <- function(WY, Rho) {
    .Call(`_bpNet_rhofit`, WY, Rho)
}

Xfit <- function(X, beta) {
    .Call(`_bpNet_Xfit`, X, beta)
}

Zfit <- function(Z, Alpha) {
    .Call(`_bpNet_Zfit`, Z, Alpha)
}

Afit <- function(A, Alpha) {
    .Call(`_bpNet_Afit`, A, Alpha)
}

genB1 <- function(X, invB0, sigma2) {
    .Call(`_bpNet_genB1`, X, invB0, sigma2)
}

genb1 <- function(X, Y, invB0, B1, b0, sigma2) {
    .Call(`_bpNet_genb1`, X, Y, invB0, B1, b0, sigma2)
}

sampleBeta <- function(X, Y, B0, b0, sigma2) {
    .Call(`_bpNet_sampleBeta`, X, Y, B0, b0, sigma2)
}

genA1 <- function(X, invA0, sigma2) {
    .Call(`_bpNet_genA1`, X, invA0, sigma2)
}

gena1 <- function(X, Y, A1, sigma2) {
    .Call(`_bpNet_gena1`, X, Y, A1, sigma2)
}

sampleCN <- function(M, S, m) {
    .Call(`_bpNet_sampleCN`, M, S, m)
}

sampleVector <- function(M, S, id, r) {
    .Call(`_bpNet_sampleVector`, M, S, id, r)
}

sampleSubAlpha <- function(X, Y, A0, unit, id, r, sigma2) {
    .Call(`_bpNet_sampleSubAlpha`, X, Y, A0, unit, id, r, sigma2)
}

sampleAlpha <- function(X, Y, A0, unit, r, sigma2) {
    .Call(`_bpNet_sampleAlpha`, X, Y, A0, unit, r, sigma2)
}

genD1 <- function(D0, coef) {
    .Call(`_bpNet_genD1`, D0, coef)
}

sampleD <- function(D0, coef, d0) {
    .Call(`_bpNet_sampleD`, D0, coef, d0)
}

genPhi0 <- function(WY, sigma2) {
    .Call(`_bpNet_genPhi0`, WY, sigma2)
}

genphi0 <- function(WY, res, Phi0, sigma2) {
    .Call(`_bpNet_genphi0`, WY, res, Phi0, sigma2)
}

samplesRho0 <- function(WY, res, lambda, sigma2) {
    .Call(`_bpNet_samplesRho0`, WY, res, lambda, sigma2)
}

abvalue0 <- function(WY, res, lambda, rho, sigma2) {
    .Call(`_bpNet_abvalue0`, WY, res, lambda, rho, sigma2)
}

sampleRho0 <- function(WY, res, lambda, rho0, rho1, sigma2) {
    .Call(`_bpNet_sampleRho0`, WY, res, lambda, rho0, rho1, sigma2)
}

genPhi <- function(wy, type, time, T, kappa, sigma2, sigma_n2) {
    .Call(`_bpNet_genPhi`, wy, type, time, T, kappa, sigma2, sigma_n2)
}

genphi <- function(wy, res, Rho_old, Rho_new, rhoZ, rhoA, type, time, T, kappa, Phi, sigma2, sigma_n2) {
    .Call(`_bpNet_genphi`, wy, res, Rho_old, Rho_new, rhoZ, rhoA, type, time, T, kappa, Phi, sigma2, sigma_n2)
}

sampleSubRho <- function(wy, res, lambda, Rho_old, Rho_new, rhoZ, rhoA, type, time, T, kappa, sigma2, sigma_n2) {
    .Call(`_bpNet_sampleSubRho`, wy, res, lambda, Rho_old, Rho_new, rhoZ, rhoA, type, time, T, kappa, sigma2, sigma_n2)
}

abvalue <- function(WY, res, Rho_old, Rho_new, lambda, rhoZ, rhoA, type, time, T, rho, kappa, sigma2, sigma_n2) {
    .Call(`_bpNet_abvalue`, WY, res, Rho_old, Rho_new, lambda, rhoZ, rhoA, type, time, T, rho, kappa, sigma2, sigma_n2)
}

sampleRho <- function(WY, res, Rho_old, lambda, rhoZ, rhoA, type, kappa, sigma2, sigma_n2) {
    .Call(`_bpNet_sampleRho`, WY, res, Rho_old, lambda, rhoZ, rhoA, type, kappa, sigma2, sigma_n2)
}

sampleRhoA <- function(Rho, rhoZ, RA0, ra0, type, kappa, sigma_n2) {
    .Call(`_bpNet_sampleRhoA`, Rho, rhoZ, RA0, ra0, type, kappa, sigma_n2)
}

sampleKappa <- function(Rho, rhoZ, rhoA, sigma_n2) {
    .Call(`_bpNet_sampleKappa`, Rho, rhoZ, rhoA, sigma_n2)
}

sampleSigman2 <- function(Rho, rhoZ, rhoA, type, kappa) {
    .Call(`_bpNet_sampleSigman2`, Rho, rhoZ, rhoA, type, kappa)
}

sampleSigma2 <- function(res) {
    .Call(`_bpNet_sampleSigma2`, res)
}

genBi <- function(k) {
    .Call(`_bpNet_genBi`, k)
}

permute <- function(omega, xi) {
    .Call(`_bpNet_permute`, omega, xi)
}

sampleG <- function(a, b) {
    .Call(`_bpNet_sampleG`, a, b)
}

rrinvgauss <- function(mu, lambda) {
    .Call(`_bpNet_rrinvgauss`, mu, lambda)
}

